export default {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_REQUEST_SUCCESS: "LOGIN_REQUEST_SUCCESS",
  LOGIN_REQUEST_FAIL: "CHECKOUT_REQUEST_FAIL",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  CURRENT_PATH: "CURRENT_PATH",
  CURRENT_PATH_RESET: "CURRENT_PATH_RESET",
};
