export default {
  CONSULT_REQUEST: "CHECKOUT_REQUEST",
  CONSULT_REQUEST_SUCCESS: "CHECKOUT_REQUEST_SUCCESS",
  CONSULT_REQUEST_FAIL: "CHECKOUT_REQUEST_FAIL",
  CALCULATE_PRICE: "CALCULTATE_PRICE",
  CONSULT_LOAD: "CONSULT_LOAD_DATA",
  CONSULT_PURCHASE: "CONSULT_PURCHASE",
  CONSULT_PURCHASE_SUCCESS: "CONSULT_PURCHASE_SUCCESS",
  CONSULT_PURCHASE_FAIL: "CONSULT_PURCHASE_FAIL",
};
